# Generated by Django 4.0.3 on 2022-03-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0003_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
