# Generated by Django 4.0.3 on 2022-04-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0006_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
