# Generated by Django 4.0.3 on 2022-04-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0008_alter_product_primary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(default='https://backcap.herokuapp.com/img/motogirl.png', upload_to='img/'),
        ),
    ]
