# Generated by Django 4.0.3 on 2022-04-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0011_alter_product_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgURL',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='New', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
